version: '3.8'

services:
  api:
    container_name: sekolahku_go
    image: sekolahku_go:latest
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - go-network
    restart: unless-stopped
networks:
  go-network:
